### ISSUE TITLE
How to reproduce the result of MixStyle?

### ISSUE THREAD

**Issue by shuhao02** [Wang-pengfei/SAGM#1]
Hi!
Thanks for providing this great repo! I have one question about the result of MixStyle result. In Table 1 and Table 2 of your paper, the results of MixStyle are seen to be conflicting. The performances of MixStyle on PACS are  85.2 and 83.9, respectively. I have noticed that the MixStyle results in Table 1 copy from SWAD. Is that mean you produce the performance in Table 2 by your code?  How can we reproduce the result of MixStyle in Table 2?
I have made some efforts to reproduce your MixStyle result, but all of them come to fail. The result is five percent under your report.
Could you release your command or code of ERM+Mixstyle? That will be very helpful to me.

Thanks in advance.

**Comment by Wang-pengfei** [comment]
Hi, thanks for your interest in our work. 

Note that the results of Mixstyle in Table 1 and Table 2 are not contradictory. For the results in Table 1, we directly used the results in SWAD (at this time, 80% of the data was used for training). And in Table 2,  we split datasets into training (60%), validation (20%), and test (20%) splits, i.e., 60% of the data was used for training. Therefore, the discrepancy between the two results is due to the difference in the experimental settings.

The result of MixStyle in Table 2 is easy to obtain; you can follow the command on SWAD to reproduce the MixStyle result: set indomain_test option to True. You can refer to [SWAD](https://github.com/khanrc/swad) for more details.

**Comment by shuhao02** [comment]
Thanks for your quick reply! 
I take your suggestions and finally reproduce the results.
