### ISSUE TITLE
why cant't i find the  repositorie about QPM and what happened?

### ISSUE THREAD

**Issue by reset-shadow** [Wang-pengfei/SAGM#2]
the open source code about  Quality-Aware Part Models for Occluded Person Re-Identification has been lost

**Comment by Wang-pengfei** [comment]
QPM was my work during my master's graduation. At that time, due to the pandemic and busy with graduation, I didn't have the opportunity to directly upload it to GitHub. Later, I had my junior colleague make a copy on the school's machine for me. You can send me an email, and I will provide you with the corresponding code. My email address is pengfei.wang@connect.polyu.hk.
